packages:
  - packages/*
  - app

catalog:
  # Polkadot API packages
  "@polkadot/api": ^16.5.4
  "@polkadot/api-augment": ^16.5.4
  "@polkadot/api-base": ^16.5.4
  "@polkadot/api-derive": ^16.5.4
  "@polkadot/rpc-provider": ^16.5.4
  "@polkadot/types": ^16.5.4
  "@polkadot/types-codec": ^16.5.4
  "@polkadot/types-known": ^16.5.4
  # Polkadot UI and utils
  "@polkadot/apps-config": ^0.169.1
  "@polkadot/ui-shared": ^3.16.4
  "@polkadot/util": ^14.0.1
  "@polkadot/util-crypto": ^14.0.1
  "@polkadot/x-ws": ^14.0.1
  # Polkadot extension
  "@polkadot/extension-base": ^0.62.6
  "@polkadot/extension-inject": ^0.62.6
