/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransferRouteImport } from './routes/_authenticated/transfer'
import { Route as AuthenticatedSettingRouteImport } from './routes/_authenticated/setting'
import { Route as AuthenticatedMultiTransferRouteImport } from './routes/_authenticated/multi-transfer'
import { Route as AuthenticatedExtrinsicRouteImport } from './routes/_authenticated/extrinsic'
import { Route as AuthenticatedDappRouteImport } from './routes/_authenticated/dapp'
import { Route as AuthenticatedCreatePureRouteImport } from './routes/_authenticated/create-pure'
import { Route as AuthenticatedCreateMultisigRouteImport } from './routes/_authenticated/create-multisig'
import { Route as AuthenticatedAnalyticRouteImport } from './routes/_authenticated/analytic'
import { Route as AuthenticatedAddressBookRouteImport } from './routes/_authenticated/address-book'
import { Route as AuthenticatedAddProxyRouteImport } from './routes/_authenticated/add-proxy'
import { Route as AuthenticatedAccountSettingRouteImport } from './routes/_authenticated/account-setting'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedTransactionsIdRouteImport } from './routes/_authenticated/transactions/$id'
import { Route as AuthenticatedExplorerUrlRouteImport } from './routes/_authenticated/explorer.$url'

const AuthenticatedFundLazyRouteImport = createFileRoute(
  '/_authenticated/fund',
)()
const AuthenticatedAssetsLazyRouteImport = createFileRoute(
  '/_authenticated/assets',
)()

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/index.lazy').then((d) => d.Route),
)
const AuthenticatedFundLazyRoute = AuthenticatedFundLazyRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/fund.lazy').then((d) => d.Route),
)
const AuthenticatedAssetsLazyRoute = AuthenticatedAssetsLazyRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/assets.lazy').then((d) => d.Route),
)
const AuthenticatedTransferRoute = AuthenticatedTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingRoute = AuthenticatedSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/setting.lazy').then((d) => d.Route),
)
const AuthenticatedMultiTransferRoute =
  AuthenticatedMultiTransferRouteImport.update({
    id: '/multi-transfer',
    path: '/multi-transfer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExtrinsicRoute = AuthenticatedExtrinsicRouteImport.update({
  id: '/extrinsic',
  path: '/extrinsic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDappRoute = AuthenticatedDappRouteImport.update({
  id: '/dapp',
  path: '/dapp',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/dapp.lazy').then((d) => d.Route),
)
const AuthenticatedCreatePureRoute = AuthenticatedCreatePureRouteImport.update({
  id: '/create-pure',
  path: '/create-pure',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/create-pure.lazy').then((d) => d.Route),
)
const AuthenticatedCreateMultisigRoute =
  AuthenticatedCreateMultisigRouteImport.update({
    id: '/create-multisig',
    path: '/create-multisig',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/create-multisig.lazy').then((d) => d.Route),
  )
const AuthenticatedAnalyticRoute = AuthenticatedAnalyticRouteImport.update({
  id: '/analytic',
  path: '/analytic',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/analytic.lazy').then((d) => d.Route),
)
const AuthenticatedAddressBookRoute =
  AuthenticatedAddressBookRouteImport.update({
    id: '/address-book',
    path: '/address-book',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/address-book.lazy').then((d) => d.Route),
  )
const AuthenticatedAddProxyRoute = AuthenticatedAddProxyRouteImport.update({
  id: '/add-proxy',
  path: '/add-proxy',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/add-proxy.lazy').then((d) => d.Route),
)
const AuthenticatedAccountSettingRoute =
  AuthenticatedAccountSettingRouteImport.update({
    id: '/account-setting',
    path: '/account-setting',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedTransactionsIdRoute =
  AuthenticatedTransactionsIdRouteImport.update({
    id: '/transactions/$id',
    path: '/transactions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/transactions/$id.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedExplorerUrlRoute =
  AuthenticatedExplorerUrlRouteImport.update({
    id: '/explorer/$url',
    path: '/explorer/$url',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/explorer.$url.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/welcome': typeof WelcomeRoute
  '/account-setting': typeof AuthenticatedAccountSettingRoute
  '/add-proxy': typeof AuthenticatedAddProxyRoute
  '/address-book': typeof AuthenticatedAddressBookRoute
  '/analytic': typeof AuthenticatedAnalyticRoute
  '/create-multisig': typeof AuthenticatedCreateMultisigRoute
  '/create-pure': typeof AuthenticatedCreatePureRoute
  '/dapp': typeof AuthenticatedDappRoute
  '/extrinsic': typeof AuthenticatedExtrinsicRoute
  '/multi-transfer': typeof AuthenticatedMultiTransferRoute
  '/setting': typeof AuthenticatedSettingRoute
  '/transfer': typeof AuthenticatedTransferRoute
  '/assets': typeof AuthenticatedAssetsLazyRoute
  '/fund': typeof AuthenticatedFundLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/explorer/$url': typeof AuthenticatedExplorerUrlRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/account-setting': typeof AuthenticatedAccountSettingRoute
  '/add-proxy': typeof AuthenticatedAddProxyRoute
  '/address-book': typeof AuthenticatedAddressBookRoute
  '/analytic': typeof AuthenticatedAnalyticRoute
  '/create-multisig': typeof AuthenticatedCreateMultisigRoute
  '/create-pure': typeof AuthenticatedCreatePureRoute
  '/dapp': typeof AuthenticatedDappRoute
  '/extrinsic': typeof AuthenticatedExtrinsicRoute
  '/multi-transfer': typeof AuthenticatedMultiTransferRoute
  '/setting': typeof AuthenticatedSettingRoute
  '/transfer': typeof AuthenticatedTransferRoute
  '/assets': typeof AuthenticatedAssetsLazyRoute
  '/fund': typeof AuthenticatedFundLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/explorer/$url': typeof AuthenticatedExplorerUrlRoute
  '/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_authenticated/account-setting': typeof AuthenticatedAccountSettingRoute
  '/_authenticated/add-proxy': typeof AuthenticatedAddProxyRoute
  '/_authenticated/address-book': typeof AuthenticatedAddressBookRoute
  '/_authenticated/analytic': typeof AuthenticatedAnalyticRoute
  '/_authenticated/create-multisig': typeof AuthenticatedCreateMultisigRoute
  '/_authenticated/create-pure': typeof AuthenticatedCreatePureRoute
  '/_authenticated/dapp': typeof AuthenticatedDappRoute
  '/_authenticated/extrinsic': typeof AuthenticatedExtrinsicRoute
  '/_authenticated/multi-transfer': typeof AuthenticatedMultiTransferRoute
  '/_authenticated/setting': typeof AuthenticatedSettingRoute
  '/_authenticated/transfer': typeof AuthenticatedTransferRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsLazyRoute
  '/_authenticated/fund': typeof AuthenticatedFundLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/explorer/$url': typeof AuthenticatedExplorerUrlRoute
  '/_authenticated/transactions/$id': typeof AuthenticatedTransactionsIdRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/welcome'
    | '/account-setting'
    | '/add-proxy'
    | '/address-book'
    | '/analytic'
    | '/create-multisig'
    | '/create-pure'
    | '/dapp'
    | '/extrinsic'
    | '/multi-transfer'
    | '/setting'
    | '/transfer'
    | '/assets'
    | '/fund'
    | '/'
    | '/explorer/$url'
    | '/transactions/$id'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/account-setting'
    | '/add-proxy'
    | '/address-book'
    | '/analytic'
    | '/create-multisig'
    | '/create-pure'
    | '/dapp'
    | '/extrinsic'
    | '/multi-transfer'
    | '/setting'
    | '/transfer'
    | '/assets'
    | '/fund'
    | '/'
    | '/explorer/$url'
    | '/transactions/$id'
    | '/transactions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/welcome'
    | '/_authenticated/account-setting'
    | '/_authenticated/add-proxy'
    | '/_authenticated/address-book'
    | '/_authenticated/analytic'
    | '/_authenticated/create-multisig'
    | '/_authenticated/create-pure'
    | '/_authenticated/dapp'
    | '/_authenticated/extrinsic'
    | '/_authenticated/multi-transfer'
    | '/_authenticated/setting'
    | '/_authenticated/transfer'
    | '/_authenticated/assets'
    | '/_authenticated/fund'
    | '/_authenticated/'
    | '/_authenticated/explorer/$url'
    | '/_authenticated/transactions/$id'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fund': {
      id: '/_authenticated/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AuthenticatedFundLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfer': {
      id: '/_authenticated/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AuthenticatedTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setting': {
      id: '/_authenticated/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthenticatedSettingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/multi-transfer': {
      id: '/_authenticated/multi-transfer'
      path: '/multi-transfer'
      fullPath: '/multi-transfer'
      preLoaderRoute: typeof AuthenticatedMultiTransferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/extrinsic': {
      id: '/_authenticated/extrinsic'
      path: '/extrinsic'
      fullPath: '/extrinsic'
      preLoaderRoute: typeof AuthenticatedExtrinsicRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dapp': {
      id: '/_authenticated/dapp'
      path: '/dapp'
      fullPath: '/dapp'
      preLoaderRoute: typeof AuthenticatedDappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-pure': {
      id: '/_authenticated/create-pure'
      path: '/create-pure'
      fullPath: '/create-pure'
      preLoaderRoute: typeof AuthenticatedCreatePureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-multisig': {
      id: '/_authenticated/create-multisig'
      path: '/create-multisig'
      fullPath: '/create-multisig'
      preLoaderRoute: typeof AuthenticatedCreateMultisigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytic': {
      id: '/_authenticated/analytic'
      path: '/analytic'
      fullPath: '/analytic'
      preLoaderRoute: typeof AuthenticatedAnalyticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/address-book': {
      id: '/_authenticated/address-book'
      path: '/address-book'
      fullPath: '/address-book'
      preLoaderRoute: typeof AuthenticatedAddressBookRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/add-proxy': {
      id: '/_authenticated/add-proxy'
      path: '/add-proxy'
      fullPath: '/add-proxy'
      preLoaderRoute: typeof AuthenticatedAddProxyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account-setting': {
      id: '/_authenticated/account-setting'
      path: '/account-setting'
      fullPath: '/account-setting'
      preLoaderRoute: typeof AuthenticatedAccountSettingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/$id': {
      id: '/_authenticated/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthenticatedTransactionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explorer/$url': {
      id: '/_authenticated/explorer/$url'
      path: '/explorer/$url'
      fullPath: '/explorer/$url'
      preLoaderRoute: typeof AuthenticatedExplorerUrlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountSettingRoute: typeof AuthenticatedAccountSettingRoute
  AuthenticatedAddProxyRoute: typeof AuthenticatedAddProxyRoute
  AuthenticatedAddressBookRoute: typeof AuthenticatedAddressBookRoute
  AuthenticatedAnalyticRoute: typeof AuthenticatedAnalyticRoute
  AuthenticatedCreateMultisigRoute: typeof AuthenticatedCreateMultisigRoute
  AuthenticatedCreatePureRoute: typeof AuthenticatedCreatePureRoute
  AuthenticatedDappRoute: typeof AuthenticatedDappRoute
  AuthenticatedExtrinsicRoute: typeof AuthenticatedExtrinsicRoute
  AuthenticatedMultiTransferRoute: typeof AuthenticatedMultiTransferRoute
  AuthenticatedSettingRoute: typeof AuthenticatedSettingRoute
  AuthenticatedTransferRoute: typeof AuthenticatedTransferRoute
  AuthenticatedAssetsLazyRoute: typeof AuthenticatedAssetsLazyRoute
  AuthenticatedFundLazyRoute: typeof AuthenticatedFundLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExplorerUrlRoute: typeof AuthenticatedExplorerUrlRoute
  AuthenticatedTransactionsIdRoute: typeof AuthenticatedTransactionsIdRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountSettingRoute: AuthenticatedAccountSettingRoute,
  AuthenticatedAddProxyRoute: AuthenticatedAddProxyRoute,
  AuthenticatedAddressBookRoute: AuthenticatedAddressBookRoute,
  AuthenticatedAnalyticRoute: AuthenticatedAnalyticRoute,
  AuthenticatedCreateMultisigRoute: AuthenticatedCreateMultisigRoute,
  AuthenticatedCreatePureRoute: AuthenticatedCreatePureRoute,
  AuthenticatedDappRoute: AuthenticatedDappRoute,
  AuthenticatedExtrinsicRoute: AuthenticatedExtrinsicRoute,
  AuthenticatedMultiTransferRoute: AuthenticatedMultiTransferRoute,
  AuthenticatedSettingRoute: AuthenticatedSettingRoute,
  AuthenticatedTransferRoute: AuthenticatedTransferRoute,
  AuthenticatedAssetsLazyRoute: AuthenticatedAssetsLazyRoute,
  AuthenticatedFundLazyRoute: AuthenticatedFundLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExplorerUrlRoute: AuthenticatedExplorerUrlRoute,
  AuthenticatedTransactionsIdRoute: AuthenticatedTransactionsIdRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
