name: Deploy staging

on:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 20

      - name: Install dependencies
        run: |
          yarn install --immutable

      - run: yarn build

      - name: Deploy to staging
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USERNAME }}
          remote_port: ${{ secrets.PORT }}
          remote_key: ${{ secrets.KEY }}
          remote_path: ${{ secrets.TARGET }}
          path: app/dist/
